// Mock transaction data
export const mockTransactions = [
  {
    id: 1,
    date: new Date('2026-01-05'),
    amount: 50000,
    category: 'Salary',
    type: 'income',
    description: 'Monthly Salary',
  },
  {
    id: 2,
    date: new Date('2026-01-07'),
    amount: 1500,
    category: 'Groceries',
    type: 'expense',
    description: 'Weekly grocery shopping',
  },
  {
    id: 3,
    date: new Date('2026-01-10'),
    amount: 120,
    category: 'Utilities',
    type: 'expense',
    description: 'Electricity bill',
  },
  {
    id: 4,
    date: new Date('2026-01-12'),
    amount: 2000,
    category: 'Entertainment',
    type: 'expense',
    description: 'Movie tickets and dinner',
  },
  {
    id: 5,
    date: new Date('2026-01-15'),
    amount: 5000,
    category: 'Rent',
    type: 'expense',
    description: 'Monthly rent payment',
  },
  {
    id: 6,
    date: new Date('2026-01-18'),
    amount: 300,
    category: 'Transportation',
    type: 'expense',
    description: 'Gas and car maintenance',
  },
  {
    id: 7,
    date: new Date('2026-01-20'),
    amount: 800,
    category: 'Healthcare',
    type: 'expense',
    description: 'Doctor visit and medications',
  },
  {
    id: 8,
    date: new Date('2026-01-22'),
    amount: 1200,
    category: 'Shopping',
    type: 'expense',
    description: 'Clothing and accessories',
  },
  {
    id: 9,
    date: new Date('2026-01-25'),
    amount: 500,
    category: 'Entertainment',
    type: 'expense',
    description: 'Concert tickets',
  },
  {
    id: 10,
    date: new Date('2026-02-05'),
    amount: 50000,
    category: 'Salary',
    type: 'income',
    description: 'Monthly Salary',
  },
  {
    id: 11,
    date: new Date('2026-02-08'),
    amount: 1400,
    category: 'Groceries',
    type: 'expense',
    description: 'Weekly grocery shopping',
  },
  {
    id: 12,
    date: new Date('2026-02-10'),
    amount: 150,
    category: 'Utilities',
    type: 'expense',
    description: 'Water and internet bills',
  },
  {
    id: 13,
    date: new Date('2026-02-12'),
    amount: 500,
    category: 'Entertainment',
    type: 'expense',
    description: 'Gaming subscription and activities',
  },
  {
    id: 14,
    date: new Date('2026-02-15'),
    amount: 5000,
    category: 'Rent',
    type: 'expense',
    description: 'Monthly rent payment',
  },
  {
    id: 15,
    date: new Date('2026-02-18'),
    amount: 250,
    category: 'Transportation',
    type: 'expense',
    description: 'Parking fees and tolls',
  },
  {
    id: 16,
    date: new Date('2026-02-20'),
    amount: 600,
    category: 'Healthcare',
    type: 'expense',
    description: 'Gym membership renewal',
  },
  {
    id: 17,
    date: new Date('2026-02-22'),
    amount: 2000,
    category: 'Shopping',
    type: 'expense',
    description: 'Electronics purchase',
  },
  {
    id: 18,
    date: new Date('2026-02-24'),
    amount: 3000,
    category: 'Entertainment',
    type: 'expense',
    description: 'Vacation planning and bookings',
  },
  {
    id: 19,
    date: new Date('2026-03-05'),
    amount: 50000,
    category: 'Salary',
    type: 'income',
    description: 'Monthly Salary',
  },
  {
    id: 20,
    date: new Date('2026-03-07'),
    amount: 1600,
    category: 'Groceries',
    type: 'expense',
    description: 'Weekly grocery shopping',
  },
  {
    id: 21,
    date: new Date('2026-03-10'),
    amount: 120,
    category: 'Utilities',
    type: 'expense',
    description: 'Electricity bill',
  },
  {
    id: 22,
    date: new Date('2026-03-12'),
    amount: 800,
    category: 'Entertainment',
    type: 'expense',
    description: 'Restaurant dinners',
  },
  {
    id: 23,
    date: new Date('2026-03-15'),
    amount: 5000,
    category: 'Rent',
    type: 'expense',
    description: 'Monthly rent payment',
  },
  {
    id: 24,
    date: new Date('2026-03-18'),
    amount: 400,
    category: 'Transportation',
    type: 'expense',
    description: 'Car service',
  },
  {
    id: 25,
    date: new Date('2026-03-20'),
    amount: 900,
    category: 'Healthcare',
    type: 'expense',
    description: 'Dental checkup and cleaning',
  },
  {
    id: 26,
    date: new Date('2026-03-22'),
    amount: 1500,
    category: 'Shopping',
    type: 'expense',
    description: 'Home furnishings',
  },
  {
    id: 27,
    date: new Date('2026-03-24'),
    amount: 700,
    category: 'Entertainment',
    type: 'expense',
    description: 'Event tickets',
  },
  {
    id: 28,
    date: new Date('2026-03-28'),
    amount: 5000,
    category: 'Freelance',
    type: 'income',
    description: 'Freelance project payment',
  },
  {
    id: 29,
    date: new Date('2026-03-30'),
    amount: 400,
    category: 'Entertainment',
    type: 'expense',
    description: 'Sports event tickets',
  },
  {
    id: 30,
    date: new Date('2026-04-02'),
    amount: 500,
    category: 'Investment',
    type: 'income',
    description: 'Dividend payment',
  },
];

export const categories = [
  { name: 'Salary', icon: '💼', color: 'text-blue-600' },
  { name: 'Freelance', icon: '🎯', color: 'text-green-600' },
  { name: 'Investment', icon: '📈', color: 'text-amber-600' },
  { name: 'Groceries', icon: '🛒', color: 'text-orange-600' },
  { name: 'Utilities', icon: '⚡', color: 'text-purple-600' },
  { name: 'Rent', icon: '🏠', color: 'text-red-600' },
  { name: 'Transportation', icon: '🚗', color: 'text-cyan-600' },
  { name: 'Entertainment', icon: '🎬', color: 'text-pink-600' },
  { name: 'Shopping', icon: '🛍️', color: 'text-yellow-600' },
  { name: 'Healthcare', icon: '⚕️', color: 'text-green-500' },
];
